# Generated by Django 3.2 on 2023-02-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('post', '0002_alter_status_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('post', 'author')},
        ),
    ]
